openapi: 3.0.1
info:
  title: Mock-first Demo
  version: 1.0.0
servers:
- url: https://m030e.wiremockapi.cloud
- url: https://git-sync.wiremockapi.cloud
paths:
  /things/{thingId}:
    get:
      description: Get things by thingId.
      operationId: getThingsByThingId
      parameters:
      - name: thingId
        in: path
        required: true
      responses:
        "200":
          description: Live Demo 5 stub 1
          content:
            application/json:
              schema:
                required:
                - stub
                type: object
                properties:
                  stub:
                    type: integer
                    format: int32
                    example: 1
                x-wiremock-hash: -879452980
              examples:
                Live Demo 5 stub 1:
                  value: |
                    {
                      "stub": 1
                    }
